import type { Topology } from "./schemas";

/** Generated from the reviewed Northern topology capture. Run generate-northern-topology.mjs to refresh. */
export const bundledTopology: {
  capturedAt: string;
  maxAgeDays: number;
  topology: Topology[];
} = {
  capturedAt: "2026-09-15T21:53:00.000Z",
  maxAgeDays: 30,
  topology: [
  {
    "lineId": "northern",
    "direction": "inbound",
    "orderedLineRoutes": [
      {
        "name": "Edgware  &harr;  Morden  via Bank",
        "naptanIds": [
          "940GZZLUEGW",
          "940GZZLUBTK",
          "940GZZLUCND",
          "940GZZLUHCL",
          "940GZZLUBTX",
          "940GZZLUGGN",
          "940GZZLUHTD",
          "940GZZLUBZP",
          "940GZZLUCFM",
          "940GZZLUCTN",
          "940GZZLUEUS",
          "940GZZLUKSX",
          "940GZZLUAGL",
          "940GZZLUODS",
          "940GZZLUMGT",
          "940GZZLUBNK",
          "940GZZLULNB",
          "940GZZLUBOR",
          "940GZZLUEAC",
          "940GZZLUKNG",
          "940GZZLUOVL",
          "940GZZLUSKW",
          "940GZZLUCPN",
          "940GZZLUCPC",
          "940GZZLUCPS",
          "940GZZLUBLM",
          "940GZZLUTBC",
          "940GZZLUTBY",
          "940GZZLUCSD",
          "940GZZLUSWN",
          "940GZZLUMDN"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Edgware  &harr;  Battersea Power Station ",
        "naptanIds": [
          "940GZZLUEGW",
          "940GZZLUBTK",
          "940GZZLUCND",
          "940GZZLUHCL",
          "940GZZLUBTX",
          "940GZZLUGGN",
          "940GZZLUHTD",
          "940GZZLUBZP",
          "940GZZLUCFM",
          "940GZZLUCTN",
          "940GZZLUMTC",
          "940GZZLUEUS",
          "940GZZLUWRR",
          "940GZZLUGDG",
          "940GZZLUTCR",
          "940GZZLULSQ",
          "940GZZLUCHX",
          "940GZZLUEMB",
          "940GZZLUWLO",
          "940GZZLUKNG",
          "940GZZNEUGST",
          "940GZZBPSUST"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Edgware  &harr;  Morden  via Charing Cross",
        "naptanIds": [
          "940GZZLUEGW",
          "940GZZLUBTK",
          "940GZZLUCND",
          "940GZZLUHCL",
          "940GZZLUBTX",
          "940GZZLUGGN",
          "940GZZLUHTD",
          "940GZZLUBZP",
          "940GZZLUCFM",
          "940GZZLUCTN",
          "940GZZLUMTC",
          "940GZZLUEUS",
          "940GZZLUWRR",
          "940GZZLUGDG",
          "940GZZLUTCR",
          "940GZZLULSQ",
          "940GZZLUCHX",
          "940GZZLUEMB",
          "940GZZLUWLO",
          "940GZZLUKNG",
          "940GZZLUOVL",
          "940GZZLUSKW",
          "940GZZLUCPN",
          "940GZZLUCPC",
          "940GZZLUCPS",
          "940GZZLUBLM",
          "940GZZLUTBC",
          "940GZZLUTBY",
          "940GZZLUCSD",
          "940GZZLUSWN",
          "940GZZLUMDN"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "High Barnet  &harr;  Morden  via Bank",
        "naptanIds": [
          "940GZZLUHBT",
          "940GZZLUTAW",
          "940GZZLUWOP",
          "940GZZLUWFN",
          "940GZZLUFYC",
          "940GZZLUEFY",
          "940GZZLUHGT",
          "940GZZLUACY",
          "940GZZLUTFP",
          "940GZZLUKSH",
          "940GZZLUCTN",
          "940GZZLUEUS",
          "940GZZLUKSX",
          "940GZZLUAGL",
          "940GZZLUODS",
          "940GZZLUMGT",
          "940GZZLUBNK",
          "940GZZLULNB",
          "940GZZLUBOR",
          "940GZZLUEAC",
          "940GZZLUKNG",
          "940GZZLUOVL",
          "940GZZLUSKW",
          "940GZZLUCPN",
          "940GZZLUCPC",
          "940GZZLUCPS",
          "940GZZLUBLM",
          "940GZZLUTBC",
          "940GZZLUTBY",
          "940GZZLUCSD",
          "940GZZLUSWN",
          "940GZZLUMDN"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "High Barnet  &harr;  Battersea Power Station ",
        "naptanIds": [
          "940GZZLUHBT",
          "940GZZLUTAW",
          "940GZZLUWOP",
          "940GZZLUWFN",
          "940GZZLUFYC",
          "940GZZLUEFY",
          "940GZZLUHGT",
          "940GZZLUACY",
          "940GZZLUTFP",
          "940GZZLUKSH",
          "940GZZLUCTN",
          "940GZZLUMTC",
          "940GZZLUEUS",
          "940GZZLUWRR",
          "940GZZLUGDG",
          "940GZZLUTCR",
          "940GZZLULSQ",
          "940GZZLUCHX",
          "940GZZLUEMB",
          "940GZZLUWLO",
          "940GZZLUKNG",
          "940GZZNEUGST",
          "940GZZBPSUST"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "High Barnet  &harr;  Morden  via Charing Cross",
        "naptanIds": [
          "940GZZLUHBT",
          "940GZZLUTAW",
          "940GZZLUWOP",
          "940GZZLUWFN",
          "940GZZLUFYC",
          "940GZZLUEFY",
          "940GZZLUHGT",
          "940GZZLUACY",
          "940GZZLUTFP",
          "940GZZLUKSH",
          "940GZZLUCTN",
          "940GZZLUMTC",
          "940GZZLUEUS",
          "940GZZLUWRR",
          "940GZZLUGDG",
          "940GZZLUTCR",
          "940GZZLULSQ",
          "940GZZLUCHX",
          "940GZZLUEMB",
          "940GZZLUWLO",
          "940GZZLUKNG",
          "940GZZLUOVL",
          "940GZZLUSKW",
          "940GZZLUCPN",
          "940GZZLUCPC",
          "940GZZLUCPS",
          "940GZZLUBLM",
          "940GZZLUTBC",
          "940GZZLUTBY",
          "940GZZLUCSD",
          "940GZZLUSWN",
          "940GZZLUMDN"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Mill Hill East  &harr;  Morden  via Bank",
        "naptanIds": [
          "940GZZLUMHL",
          "940GZZLUFYC",
          "940GZZLUEFY",
          "940GZZLUHGT",
          "940GZZLUACY",
          "940GZZLUTFP",
          "940GZZLUKSH",
          "940GZZLUCTN",
          "940GZZLUEUS",
          "940GZZLUKSX",
          "940GZZLUAGL",
          "940GZZLUODS",
          "940GZZLUMGT",
          "940GZZLUBNK",
          "940GZZLULNB",
          "940GZZLUBOR",
          "940GZZLUEAC",
          "940GZZLUKNG",
          "940GZZLUOVL",
          "940GZZLUSKW",
          "940GZZLUCPN",
          "940GZZLUCPC",
          "940GZZLUCPS",
          "940GZZLUBLM",
          "940GZZLUTBC",
          "940GZZLUTBY",
          "940GZZLUCSD",
          "940GZZLUSWN",
          "940GZZLUMDN"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Mill Hill East  &harr;  Morden  via Charing Cross",
        "naptanIds": [
          "940GZZLUMHL",
          "940GZZLUFYC",
          "940GZZLUEFY",
          "940GZZLUHGT",
          "940GZZLUACY",
          "940GZZLUTFP",
          "940GZZLUKSH",
          "940GZZLUCTN",
          "940GZZLUMTC",
          "940GZZLUEUS",
          "940GZZLUWRR",
          "940GZZLUGDG",
          "940GZZLUTCR",
          "940GZZLULSQ",
          "940GZZLUCHX",
          "940GZZLUEMB",
          "940GZZLUWLO",
          "940GZZLUKNG",
          "940GZZLUOVL",
          "940GZZLUSKW",
          "940GZZLUCPN",
          "940GZZLUCPC",
          "940GZZLUCPS",
          "940GZZLUBLM",
          "940GZZLUTBC",
          "940GZZLUTBY",
          "940GZZLUCSD",
          "940GZZLUSWN",
          "940GZZLUMDN"
        ],
        "serviceType": "Regular"
      }
    ],
    "stopPointSequences": []
  },
  {
    "lineId": "northern",
    "direction": "outbound",
    "orderedLineRoutes": [
      {
        "name": "Battersea Power Station  &harr;  Edgware ",
        "naptanIds": [
          "940GZZBPSUST",
          "940GZZNEUGST",
          "940GZZLUKNG",
          "940GZZLUWLO",
          "940GZZLUEMB",
          "940GZZLUCHX",
          "940GZZLULSQ",
          "940GZZLUTCR",
          "940GZZLUGDG",
          "940GZZLUWRR",
          "940GZZLUEUS",
          "940GZZLUMTC",
          "940GZZLUCTN",
          "940GZZLUCFM",
          "940GZZLUBZP",
          "940GZZLUHTD",
          "940GZZLUGGN",
          "940GZZLUBTX",
          "940GZZLUHCL",
          "940GZZLUCND",
          "940GZZLUBTK",
          "940GZZLUEGW"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Battersea Power Station  &harr;  High Barnet ",
        "naptanIds": [
          "940GZZBPSUST",
          "940GZZNEUGST",
          "940GZZLUKNG",
          "940GZZLUWLO",
          "940GZZLUEMB",
          "940GZZLUCHX",
          "940GZZLULSQ",
          "940GZZLUTCR",
          "940GZZLUGDG",
          "940GZZLUWRR",
          "940GZZLUEUS",
          "940GZZLUMTC",
          "940GZZLUCTN",
          "940GZZLUKSH",
          "940GZZLUTFP",
          "940GZZLUACY",
          "940GZZLUHGT",
          "940GZZLUEFY",
          "940GZZLUFYC",
          "940GZZLUWFN",
          "940GZZLUWOP",
          "940GZZLUTAW",
          "940GZZLUHBT"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Morden  &harr;  Edgware  via Bank",
        "naptanIds": [
          "940GZZLUMDN",
          "940GZZLUSWN",
          "940GZZLUCSD",
          "940GZZLUTBY",
          "940GZZLUTBC",
          "940GZZLUBLM",
          "940GZZLUCPS",
          "940GZZLUCPC",
          "940GZZLUCPN",
          "940GZZLUSKW",
          "940GZZLUOVL",
          "940GZZLUKNG",
          "940GZZLUEAC",
          "940GZZLUBOR",
          "940GZZLULNB",
          "940GZZLUBNK",
          "940GZZLUMGT",
          "940GZZLUODS",
          "940GZZLUAGL",
          "940GZZLUKSX",
          "940GZZLUEUS",
          "940GZZLUCTN",
          "940GZZLUCFM",
          "940GZZLUBZP",
          "940GZZLUHTD",
          "940GZZLUGGN",
          "940GZZLUBTX",
          "940GZZLUHCL",
          "940GZZLUCND",
          "940GZZLUBTK",
          "940GZZLUEGW"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Morden  &harr;  Mill Hill East  via Bank",
        "naptanIds": [
          "940GZZLUMDN",
          "940GZZLUSWN",
          "940GZZLUCSD",
          "940GZZLUTBY",
          "940GZZLUTBC",
          "940GZZLUBLM",
          "940GZZLUCPS",
          "940GZZLUCPC",
          "940GZZLUCPN",
          "940GZZLUSKW",
          "940GZZLUOVL",
          "940GZZLUKNG",
          "940GZZLUEAC",
          "940GZZLUBOR",
          "940GZZLULNB",
          "940GZZLUBNK",
          "940GZZLUMGT",
          "940GZZLUODS",
          "940GZZLUAGL",
          "940GZZLUKSX",
          "940GZZLUEUS",
          "940GZZLUCTN",
          "940GZZLUKSH",
          "940GZZLUTFP",
          "940GZZLUACY",
          "940GZZLUHGT",
          "940GZZLUEFY",
          "940GZZLUFYC",
          "940GZZLUMHL"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Morden  &harr;  High Barnet  via Bank",
        "naptanIds": [
          "940GZZLUMDN",
          "940GZZLUSWN",
          "940GZZLUCSD",
          "940GZZLUTBY",
          "940GZZLUTBC",
          "940GZZLUBLM",
          "940GZZLUCPS",
          "940GZZLUCPC",
          "940GZZLUCPN",
          "940GZZLUSKW",
          "940GZZLUOVL",
          "940GZZLUKNG",
          "940GZZLUEAC",
          "940GZZLUBOR",
          "940GZZLULNB",
          "940GZZLUBNK",
          "940GZZLUMGT",
          "940GZZLUODS",
          "940GZZLUAGL",
          "940GZZLUKSX",
          "940GZZLUEUS",
          "940GZZLUCTN",
          "940GZZLUKSH",
          "940GZZLUTFP",
          "940GZZLUACY",
          "940GZZLUHGT",
          "940GZZLUEFY",
          "940GZZLUFYC",
          "940GZZLUWFN",
          "940GZZLUWOP",
          "940GZZLUTAW",
          "940GZZLUHBT"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Morden  &harr;  Edgware  via Charing Cross",
        "naptanIds": [
          "940GZZLUMDN",
          "940GZZLUSWN",
          "940GZZLUCSD",
          "940GZZLUTBY",
          "940GZZLUTBC",
          "940GZZLUBLM",
          "940GZZLUCPS",
          "940GZZLUCPC",
          "940GZZLUCPN",
          "940GZZLUSKW",
          "940GZZLUOVL",
          "940GZZLUKNG",
          "940GZZLUWLO",
          "940GZZLUEMB",
          "940GZZLUCHX",
          "940GZZLULSQ",
          "940GZZLUTCR",
          "940GZZLUGDG",
          "940GZZLUWRR",
          "940GZZLUEUS",
          "940GZZLUMTC",
          "940GZZLUCTN",
          "940GZZLUCFM",
          "940GZZLUBZP",
          "940GZZLUHTD",
          "940GZZLUGGN",
          "940GZZLUBTX",
          "940GZZLUHCL",
          "940GZZLUCND",
          "940GZZLUBTK",
          "940GZZLUEGW"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Morden  &harr;  Mill Hill East  via Charing Cross",
        "naptanIds": [
          "940GZZLUMDN",
          "940GZZLUSWN",
          "940GZZLUCSD",
          "940GZZLUTBY",
          "940GZZLUTBC",
          "940GZZLUBLM",
          "940GZZLUCPS",
          "940GZZLUCPC",
          "940GZZLUCPN",
          "940GZZLUSKW",
          "940GZZLUOVL",
          "940GZZLUKNG",
          "940GZZLUWLO",
          "940GZZLUEMB",
          "940GZZLUCHX",
          "940GZZLULSQ",
          "940GZZLUTCR",
          "940GZZLUGDG",
          "940GZZLUWRR",
          "940GZZLUEUS",
          "940GZZLUMTC",
          "940GZZLUCTN",
          "940GZZLUKSH",
          "940GZZLUTFP",
          "940GZZLUACY",
          "940GZZLUHGT",
          "940GZZLUEFY",
          "940GZZLUFYC",
          "940GZZLUMHL"
        ],
        "serviceType": "Regular"
      },
      {
        "name": "Morden  &harr;  High Barnet  via Charing Cross",
        "naptanIds": [
          "940GZZLUMDN",
          "940GZZLUSWN",
          "940GZZLUCSD",
          "940GZZLUTBY",
          "940GZZLUTBC",
          "940GZZLUBLM",
          "940GZZLUCPS",
          "940GZZLUCPC",
          "940GZZLUCPN",
          "940GZZLUSKW",
          "940GZZLUOVL",
          "940GZZLUKNG",
          "940GZZLUWLO",
          "940GZZLUEMB",
          "940GZZLUCHX",
          "940GZZLULSQ",
          "940GZZLUTCR",
          "940GZZLUGDG",
          "940GZZLUWRR",
          "940GZZLUEUS",
          "940GZZLUMTC",
          "940GZZLUCTN",
          "940GZZLUKSH",
          "940GZZLUTFP",
          "940GZZLUACY",
          "940GZZLUHGT",
          "940GZZLUEFY",
          "940GZZLUFYC",
          "940GZZLUWFN",
          "940GZZLUWOP",
          "940GZZLUTAW",
          "940GZZLUHBT"
        ],
        "serviceType": "Regular"
      }
    ],
    "stopPointSequences": []
  }
],
};
